services:
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: ai_vector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: vector_playground
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: "no"

  redis:
    image: redis:alpine
    container_name: pulseguard_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: "no"

volumes:
  pgvector_data:
  redis_data: